version: 0.0.{build}

branches:
  except:
    - gh-pages

skip_commits:
  message: Update README.md

shallow_clone: true

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

platform: Any CPU

configuration: Release

build:
  project: ManagedBass.sln
  verbosity: minimal

test:
  categories:
    - CI

deploy:
  - provider: GitHub
    artifact: bin\Release\ManagedBass.dll
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
