name: Build Test
on:
  push:
   branches:
     - master
     - automation/github-action-for-package-publishing
  pull_request:
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  SOLUTION_FILE: ManagedBass.sln
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore
        working-directory: ${{ github.workspace }}/src
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ${{ github.workspace }}/src
      - name: Test
        run: dotnet test -c Release
        working-directory: ${{ github.workspace }}/src